namespace:
  name: demo

image:
  repository: nginx
  tag: alpine
  imagePullPolicy: IfNotPresent

resources:
  cpu: 50m
  mem: 256Mi

service:
  type: ClusterIP
  port: 8111

configmap:
  data: "version:alpine"

replicaCount: 1